Fail faster for missing env vars, login issues.
Update odoo-ci-dind.yaml

Update odoo-ci-dind.yaml

Update odoo-ci-dind.yaml

Update odoo-ci-dind.yaml

Update odoo-ci-dind.yaml

Update odoo-ci-dind.yaml to check workflow conditions for allowed branches in the script rather than in the workflow rules, bypassing gitlab CI issue where variables are not expanded in regex strings.

Revert "Update odoo-ci-dind.yaml to check workflow conditions for allowed branches in the script rather than in the workflow rules, bypassing gitlab CI issue where variables are not expanded in regex strings."

This reverts commit 5a3df4d8e8631f8eb9bd899626de7f54dfacdb6f.

Revert "Update odoo-ci-dind.yaml"

This reverts commit 2bd8778817f3eb9aea16bd553d14cf4ee9303710.

Revert "Update odoo-ci-dind.yaml"

This reverts commit 527fbfd0549b244d38277b2e4e1c7b238a1c7a2e.

Revert "Update odoo-ci-dind.yaml"

This reverts commit 36534a4ee66be7ee67afe37b477ad0b2dc511d14.

Revert "Update odoo-ci-dind.yaml"

This reverts commit 675e29556c0b893c04072f666d26734f89c9c227.

Revert "Update odoo-ci-dind.yaml"

This reverts commit 4ee1603d64c1eb84a8d55f184fb0cdaad86e9d68.

diff --git a/odoo-ci-dind.yaml b/odoo-ci-dind.yaml
--- a/odoo-ci-dind.yaml
+++ b/odoo-ci-dind.yaml
@@ -36,8 +36,19 @@ build:
   script:
     - |
       set -x
+      
+      # Validate essential environment variables
+      if [ -z "$CI_REGISTRY" ] || [ -z "$CI_DEPLOY_USER" ] || [ -z "$CI_DEPLOY_PASSWORD" ]; then
+        echo "ERROR: Missing required Docker registry credentials"
+        exit 1
+      fi
+      
       # Check docker is running or fail fast
       docker image ls
+
+      # Login to Docker registry or fail fast
+      echo "${CI_DEPLOY_PASSWORD}" | docker login ${CI_REGISTRY} -u "${CI_DEPLOY_USER}" --password-stdin
+      
       # Install git and ssh
       apk add --no-cache git openssh-client bash shadow
 
@@ -105,8 +116,6 @@ build:
       # Set build date
       BUILD_DATE=$(date +%Y-%m-%d)
 
-      # Login to Docker registry
-      echo "${CI_DEPLOY_PASSWORD}" | docker login ${CI_REGISTRY} -u "${CI_DEPLOY_USER}" --password-stdin
 
       # Build the Docker image with date and latest tags
       docker build \
